In [ ]:
2022.08.20

In [14]:
import numpy as np
import pandas as pd
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.10.0.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : zh_CN.UTF-8
LOCALE           : Chinese (Simplified)_China.936

pandas           : 1.4.0
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 61.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.3.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : No

# 预备知识
## 列表推导式与条件赋值

## 匿名函数与map方法

## zip对象与enumerate方法

# Numpy 基础
## np数组的构造

## np数组的变形与合并

## np数组的切片与索引

## 常用函数

## 广播机制

## 向量与矩阵的计算

# 练习
## EX1

In [47]:
M1 = np.random.randn(2,3)
M2 = np.random.randn(3,4)
res = np.empty((M1.shape[0],M2.shape[1]))
print(M1.shape,M2.shape,res.shape)

(2, 3) (3, 4) (2, 4)


In [48]:
M1

array([[-0.18775266, -0.91381401, -0.68493255],
       [-0.3132573 , -0.13877611,  0.83610451]])

In [49]:
M2

array([[-0.34795759, -0.44560839, -0.35562451,  0.09535585],
       [ 1.45664096, -1.91884583, -0.82005848, -1.72828048],
       [-0.15413475,  0.33152889, -1.44101442, -0.27714041]])

In [50]:
for i in range(M1.shape[0]):
    for j in range(M2.shape[1]):
        item = 0
        for k in range(M1.shape[1]):
            item += M1[i][k] * M2[k][j]
        res[i][j] = item
(np.abs((M1@M2 - res) < 1e-15)).all() # 排除数值误差

True

In [51]:
res

array([[-1.16019705,  1.61005745,  1.80314806,  1.7512461 ],
       [-0.22201947,  0.68307284, -0.97963215, -0.02174522]])

In [52]:
M12=np.array([[sum(M1[i][k] * M2[k][j] for k in range(M1.shape[1])) for j in range(M2.shape[1])] for i in range(M1.shape[0]) ])
M12

array([[-1.16019705,  1.61005745,  1.80314806,  1.7512461 ],
       [-0.22201947,  0.68307284, -0.97963215, -0.02174522]])

In [53]:
M12.shape

(2, 4)

## EX2

In [54]:
A = np.arange(1,10).reshape(3,-1)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
B = A*(1/A).sum(1).reshape(-1,1)
B

array([[1.83333333, 3.66666667, 5.5       ],
       [2.46666667, 3.08333333, 3.7       ],
       [2.65277778, 3.03174603, 3.41071429]])