joyful pandas 学习笔记    
2022.08.21 update  

学习资料:  
- 开源内容：  http://joyfulpandas.datawhale.club/
- 配套代码：  https://github.com/datawhalechina/joyful-pandas   
- 学习视频：  https://www.bilibili.com/video/BV1tK4y177AF
- 配套教材：  《Pandas数据处理与分析》 https://item.jd.com/13268767.html

In [64]:
import numpy as np
import pandas as pd
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : bb1f651536508cdfef8550f93ace7849b00046ee
python           : 3.10.0.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : zh_CN.UTF-8
LOCALE           : Chinese (Simplified)_China.936

pandas           : 1.4.0
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 61.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.3.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : No

# Python基础
## 列表推导式与条件赋值  
1.列表推导式目的：快速生成新的列表，简化代码   
2.列表推导式格式：[表达式 for 多个if或/和 for 语句]    

### 列表推导式与循环
基本上, 大多数时候, 列表推导式与循环可以实现我们的需求. 列表推导式的优点体现在能够使得代码更加简洁和清晰上, 但过早为了追求简洁而滥用列表推导式, 一方面会降低代码的可读性, 另一方, 过早进行优化也将导致大量时间的浪费.

In [74]:
def my_func(lst):
    new_lst=[]
    for i in range(len(lst)):
        new_lst.append(lst[i]**2)
    return new_lst

In [76]:
# 循环
lst=[0,1,2,3,4]
%timeit my_func(lst)

2.24 µs ± 13.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [77]:
#列表推导式
lst=[0,1,2,3,4]
%timeit [x**2 for x in lst]

1.75 µs ± 7.86 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## 匿名函数与map方法

## zip对象与enumerate方法

# Numpy 基础



## np数组的构造

## np数组的变形与合并

## np数组的切片与索引

## 常用函数

一些函数方法

### np.random.choice()函数

作用：官方文档上说的是“Generates a random sample from a given 1-D array”，大体意思是从给定的一维数组中产生随机样本，超过一维的数组是不能输入choice函数的。
用法：choice(arrayA, size=None, replace=True, p=None). 其中，size可以为一个整数或者一个由整数构成的元组，代表choice函数输出的结构；replace参数用来选择有放回和无放回抽样；p参数是一个1-D array,是可选的参数，如果要赋值的话，长度必须和arrayA参数的长度一致，而且所有元素的和必须为1，因为p参数代表的是arrayA中每一个元素被选中的概率。
例子

myarray=np.array(['a', 'b', 'c', 'd'])
np.random.choice(my_list, 2, replace=False, p=[0.1, 0.7, 0.1 ,0.1])
>输出：['a' 'b']
1
2
3




### np.reshape()与np.resize()的区别

np.reshape()与np.resize()作用都是一样的，区别在于np.resize()会直接在原数组上做修改，而np.reshape是生成一个修改后的副本。我在做实验的时候使用 np.arange(10).resize((2,5)）这种写法，输出的不是新数组，而是None。而使用np.arange(10).reshape((2,5)）就能产生正确的输出。不太清楚其中具体的原理，希望有同学能帮忙解释一下。


### numpy.r_[]与numpy.c_[]

np.r_[]和numpy.c_[]都是拼接数组的，但他们不是函数，没有输入和输出，只是一个操作，所以不用(),而是用索引[]符号。简单来说，在二维数组上，np.r_[]操作可以表示为上下合并（r代表的就是row,显然是在数组的行方向进行合并），np.c_[]操作可以表示为左右合并（c代表的就是column）例如

x=np.arange(4).reshape((2,2))
np.r_[x,x]
>输出为：
>[[0 1]  
 [2 3]  
 [0 1]  
 [2 3]]  
np.c_[x,x]
>输出为：
>[[0 1 0 1]
 [2 3 2 3]]
1
2
3
4
5
6
7
8
9
10
11
np.r_[]和np.c_[]的更一般的用法其实还挺复杂，官方文档上给的解释没有太理解。。。



### numpy.ix_()函数

np.ix_()是一个函数，可以快速构建索引数组，比如:

In [58]:
a=np.arange(6).reshape((2,3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
[ [a[0,1]*a[0,2]], [a[1,1]*a[1,2]] ]

[[2], [20]]

In [61]:
x[np.ix_([0,1],[1,2])] 

NameError: name 'x' is not defined

In [60]:
np.ix_([0,1],[1,2])

(array([[0],
        [1]]),
 array([[1, 2]]))

In [ ]:
可以很明显的看出，x[np.ix_([0,1],[1,2])] 就是
[ [a[0,1] a[0,2]], [a[1,1] a[1,2]] ], 所以，np.ix_([0,1],[1,2)]
相当于在[0,1]和[1,2]这两个序列之间做了笛卡尔乘积，再把笛卡尔乘积后的结果作为索引。


### nan*统计函数

numpy中像max,min,mean 等等统计函数，不能处理有缺失值的数组，因此需要先把缺失值去掉再统计，过程十分麻烦,并且还会修改原始数据, 有了 nan* 这种类型的函数,例如 nanmax,nanmin,nanmin 等等, 就可以直接忽略缺失值进行计算,更加方便.


## 广播机制

## 向量与矩阵的计算

# 练习
## EX1

In [47]:
M1 = np.random.randn(2,3)
M2 = np.random.randn(3,4)
res = np.empty((M1.shape[0],M2.shape[1]))
print(M1.shape,M2.shape,res.shape)

(2, 3) (3, 4) (2, 4)


In [48]:
M1

array([[-0.18775266, -0.91381401, -0.68493255],
       [-0.3132573 , -0.13877611,  0.83610451]])

In [49]:
M2

array([[-0.34795759, -0.44560839, -0.35562451,  0.09535585],
       [ 1.45664096, -1.91884583, -0.82005848, -1.72828048],
       [-0.15413475,  0.33152889, -1.44101442, -0.27714041]])

In [50]:
for i in range(M1.shape[0]):
    for j in range(M2.shape[1]):
        item = 0
        for k in range(M1.shape[1]):
            item += M1[i][k] * M2[k][j]
        res[i][j] = item
(np.abs((M1@M2 - res) < 1e-15)).all() # 排除数值误差

True

In [51]:
res

array([[-1.16019705,  1.61005745,  1.80314806,  1.7512461 ],
       [-0.22201947,  0.68307284, -0.97963215, -0.02174522]])

In [52]:
M12=np.array([[sum(M1[i][k] * M2[k][j] for k in range(M1.shape[1])) for j in range(M2.shape[1])] for i in range(M1.shape[0]) ])
M12

array([[-1.16019705,  1.61005745,  1.80314806,  1.7512461 ],
       [-0.22201947,  0.68307284, -0.97963215, -0.02174522]])

In [53]:
M12.shape

(2, 4)

## EX2

In [54]:
A = np.arange(1,10).reshape(3,-1)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
B = A*(1/A).sum(1).reshape(-1,1)
B

array([[1.83333333, 3.66666667, 5.5       ],
       [2.46666667, 3.08333333, 3.7       ],
       [2.65277778, 3.03174603, 3.41071429]])